version: '3'
services:
  web:
    container_name: lifemr-web
    init: true
    build: 
      context: ./web
      target: development
    command: sh -c "npm install; npm run dev --host"
    environment:
      - PORT=80
    ports:
      - '80:80'
    working_dir: /usr/src/lifemr-frontend
    volumes:
      - ./web:/usr/src/lifemr-frontend/

  api:
    container_name: lifemr-api
    init: true
    build: 
      context: ./api
      target: development
    command: sh -c "pip install --no-cache-dir -r requirements.txt --upgrade pip; uvicorn src.main:app --host 0.0.0.0 --port 7000 --reload"
    environment:
      - PORT=7000
    ports:
      - '7000:7000'
    working_dir: /usr/src/lifemr-backend
    volumes:
      - ./api:/usr/src/lifemr-backend/

  postgres:
    container_name: lifemr-db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: lifemr
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: pass
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data/
